name: Terraform Module Releaser
on:
  pull_request:
    types: [opened, reopened, synchronize, closed] # Releaser does dry run on all stages of PR, but closed/merged to main executes a real release, (closed required)
    branches: [main]

permissions:
  contents: write # write tags, create releases, and push to the wiki
  pull-requests: write # write dry run comments

concurrency:
  group: module-releaser-${{ github.event.pull_request.number }} # Creates a group for the PR so two runs can't simultaneously execute on the same PR
  cancel-in-progress: false # Won't cancel in flight runs

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: techpivot/terraform-module-releaser@v2
        with:
          module-path-ignore: "examples/**"   # keep examples from being released
          default-first-tag: v0.1.0
